version: '3'

#Each service runs in a seperate container
services:

  #the name of the service
  express-service:

    #shorthand name for the container
    container_name: fs-petshop

    #build path to the Dockerfile
    build: .

    #create a bind mount so local changes show up in the container
    #for development (lots of changes - restarting the container would be slow)
    volumes: 
      - ./:/app

    #map the ports <outside container>:<inside container>
    ports: 
      - "8000:8000"

    #Override the entrypoint in the Dockerfile
    command: ["nodemon", "restfulExpressServer.js"]